# Информация по дефолтным параметрам:

# name: отображаемое имя зачарования
# chance: шанс выбить на чародейском столе
# anvil_cost: цена в наковальне, суммируется с накладываемым уровнем
# min_table_level: минимальный уровень чародейского стола для выбивания чара

# Проверка плагина на обновления
update-check: true

enchants:

  jumper:
    name: Попрыгун
    chance: 10
    potion_effect: JUMP
    effect_amplifier: 1
    anvil_cost: 3
    min_table_level: 27

  bulldozer:
    name: Бульдозер
    chance: 7
    anvil_cost: 5
    min_table_level: 16

  melting:
    name: Авто-плавка
    chance: 10
    anvil_cost: 4
    min_table_level: 8

  magnet:
    name: Магнит
    chance: 6
    anvil_cost: 3
    min_table_level: 8

  pinger:
    name: Пингер
    chance: 12
    anvil_cost: 2
    min_table_level: 4

  web:
    name: Паутина
    chance: 4
    anvil_cost: 6
    min_table_level: 12

  mega_bulldozer:
    chance: 2
    name: Мега-бульдозер
    anvil_cost: 6
    min_table_level: 40

  woodcutter:
    name: Дровосек
    chance: 5
    anvil_cost: 4
    min_table_level: 16

  lavawalker:
    name: Лаваход
    chance: 2
    anvil_cost: 5
    min_table_level: 27

  greener:
    name: Озеленитель
    chance: 7
    anvil_cost: 1
    min_table_level: 16

  stupor:
    name: Ступор
    chance: 2
    anvil_cost: 5
    min_table_level: 4

  scout:
    name: Скаут
    chance: 6
    anvil_cost: 4
    min_table_level: 8

  pulling:
    name: Притяжение
    chance: 2
    anvil_cost: 3
    min_table_level: 8

  comeback:
    name: Возвращение
    chance: 4
    anvil_cost: 6
    min_table_level: 12

  bomber:
    name: Подрывник
    chance: 1
    anvil_cost: 3
    min_table_level: 9

  sniper:
    name: Снайпер
    chance: 6
    anvil_cost: 3
    min_table_level: 4

  detect:
    name: Детекция
    chance: 1
    anvil_cost: 3
    min_table_level: 24

  poison:
    name: Яд
    chance: 4
    anvil_cost: 4
    min_table_level: 12

  vamp:
    name: Вампиризм
    chance: 5
    anvil_cost: 2
    min_table_level: 12

  not_stable:
    name: Нестабильный
    chance: 1
    anvil_cost: 3
    min_table_level: 27