# Информация по дефолтным параметрам:

# name: отображаемое имя зачарования
# chance: шанс выбить на чародейском столе
# anvil_cost: цена в наковальне, суммируется с накладываемым уровнем
# min_table_level: минимальный уровень чародейского стола для выбивания чара

# Проверка плагина на обновления
update-check: true

enchants:

  jumper:
    name: Попрыгун
    chance: 10
    potion_effect: JUMP
    effect_amplifier: 1
    anvil_cost: 3
    min_table_level: 27

  bulldozer:
    name: Бульдозер
    chance: 7
    anvil_cost: 5
    min_table_level: 16
    sensitivity:
      vertical: 0.83

  melting:
    name: Авто-плавка
    chance: 10
    anvil_cost: 4
    min_table_level: 8
    particle:
      type: FLAME
      count: 3
      speed: 0.03
      delta_x: 0.045
      delta_z: 0.045
      delta_y: 0.045
    melted: # ЧТО_ПЛАВИТЬ: ЧТО_ПОЛУЧАТЬ
      IRON_ORE: IRON_INGOT
      GOLD_ORE: GOLD_INGOT
      ANCIENT_DEBRIS: NETHERITE_SCRAP
      SAND: GLASS_BLOCK


  magnet:
    name: Магнит
    chance: 6
    anvil_cost: 3
    min_table_level: 8
    sound:
      type: ENTITY_ITEM_PICKUP
      yaw: 1
      pitch: 1
    magnitude:
      - IRON_INGOT
      - IRON_ORE
      - DIAMOND
      - DIAMOND_ORE
      - GOLD_INGOT
      - GOLD_ORE
      - LAPIS_LAZULI
      - LAPIS_ORE
      - OBSIDIAN
      - REDSTONE
      - REDSTONE_ORE
      - GLASS
      - SAND
      - EMERALD
      - EMERALD_ORE
      - COAL
      - COAL_ORE
      - ANCIENT_DEBRIS
      - GOLD_NUGGET
      - CHARCOAL

  pinger:
    name: Пингер
    chance: 12
    anvil_cost: 2
    min_table_level: 4
    percent_to_ping: 25
    sound:
      type: BLOCK_NOTE_BLOCK_BASS
      yaw: 2
      pitch: 2

  web:
    name: Паутина
    chance: 4
    anvil_cost: 6
    min_table_level: 12
    max_ores: 30
    particle:
      type: FIREWORKS_SPARK
      count: 1
      speed: 0.2
      delta_x: 0.03
      delta_z: 0.03
      delta_y: 0.03

  mega_bulldozer:
    chance: 2
    name: Мега-бульдозер
    anvil_cost: 6
    min_table_level: 40

  woodcutter:
    name: Дровосек
    chance: 5
    anvil_cost: 4
    min_table_level: 16
    first:
      max_wood: 20
    second:
      max_wood: 40

  lavawalker:
    name: Лаваход
    chance: 2
    anvil_cost: 5
    min_table_level: 27
    main_block: OBSIDIAN
    second_block: BASALT

  greener:
    name: Озеленитель
    chance: 7
    anvil_cost: 1
    min_table_level: 16
    upgrade_step: 1
    particle:
      type: VILLAGER_HAPPY
      count: 6
      speed: 0.3
      delta_x: 0.5
      delta_z: 0.3
      delta_y: 0.05

  stupor:
    name: Ступор
    chance: 2
    anvil_cost: 5
    min_table_level: 4

  scout:
    name: Скаут
    chance: 6
    anvil_cost: 4
    min_table_level: 8

  pulling:
    name: Притяжение
    chance: 2
    anvil_cost: 3
    min_table_level: 8

  comeback:
    name: Возвращение
    chance: 4
    anvil_cost: 6
    min_table_level: 12

  bomber:
    name: Подрывник
    chance: 1
    anvil_cost: 3
    min_table_level: 9

  sniper:
    name: Снайпер
    chance: 6
    anvil_cost: 3
    min_table_level: 4

  detect:
    name: Детекция
    chance: 11
    anvil_cost: 3
    min_table_level: 24
    first:
      effect_chance: 0.2 # Шанс выдачи эффекта при ударе
      effect_duration: 2 # Длительность в секундах
      effect_amplifier: 1 # уровень эффекта(мин: 1)
    second:
      effect_chance: 0.3
      effect_duration: 3
      effect_amplifier: 1
    third:
      effect_chance: 0.4
      effect_duration: 4
      effect_amplifier: 1

  poison:
    name: Яд
    chance: 4
    anvil_cost: 4
    min_table_level: 12

  vamp:
    name: Вампиризм
    chance: 5
    anvil_cost: 2
    min_table_level: 12

  not_stable:
    name: Нестабильный
    chance: 1
    anvil_cost: 3
    min_table_level: 27

  experienced:
    name: Опытный
    chance: 4
    anvil_cost: 3
    min_table_level: 8

  impenetrable:
    name: Непробиваемый
    chance: 5
    anvil_cost: 5
    min_table_level: 20
    protection_piece: 0.05 # процент защиты на 1 часть брони! фулл сет -> 0.2 -> 20%
    max_protection: 0.2 # максимальный процент защиты
    chance_protection: 0.1 # Шанс защиты
    sound:
      type: ITEM_SHIELD_BLOCK
      yaw: 1
      pitch: 1