name: cEnchants
version: '${project.version}'
main: su.trident.cenchants.CEnchants
api-version: '1.16'
depend: [ WorldGuard ]
commands:
  ce:
    permission: trident.enchant
    aliases:
      - cenchants
permissions:
  trident.admin:
    default: op
